"""rendimento em contas remuneradas

As colunas novas entram com server_default porque a tabela ja tem linhas:
sem ele, o Postgres recusa adicionar uma coluna NOT NULL. O default fica
no banco de proposito -- e o que torna a migration reexecutavel em bases
que ja tinham contas.

Revision ID: d5b4b0b9b852
Revises: af57ca9c04e5
Create Date: 2026-09-11 14:08:19.010447
"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd5b4b0b9b852'
down_revision: str | None = 'af57ca9c04e5'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('yield_type', sa.Enum('none', 'cdi_percent', name='yield_type', native_enum=False, length=16), nullable=False, server_default='none'))
    op.add_column('account', sa.Column('yield_rate', sa.Numeric(precision=7, scale=4), nullable=False, server_default='0'))
    op.add_column('account', sa.Column('yield_started_on', sa.Date(), nullable=True))
    op.add_column('account', sa.Column('last_yield_month', sa.Date(), nullable=True))
    op.add_column('transaction', sa.Column('yield_month', sa.Date(), nullable=True))
    op.create_index('uq_transaction_yield_month', 'transaction', ['account_id', 'yield_month'], unique=True, postgresql_where=sa.text('yield_month IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_transaction_yield_month', table_name='transaction', postgresql_where=sa.text('yield_month IS NOT NULL'))
    op.drop_column('transaction', 'yield_month')
    op.drop_column('account', 'last_yield_month')
    op.drop_column('account', 'yield_started_on')
    op.drop_column('account', 'yield_rate')
    op.drop_column('account', 'yield_type')
    # ### end Alembic commands ###
