"""estrutura inicial

Revision ID: 41437c295355
Revises: 
Create Date: 2026-09-11 10:20:04.914516
"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '41437c295355'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user'))
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=False)
    op.create_table('account',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('bank', sa.String(length=80), nullable=True),
    sa.Column('type', sa.Enum('checking', 'savings', 'investment', 'cash', name='account_type', native_enum=False, length=16), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_account_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account'))
    )
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=False)
    op.create_table('category',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('expense', 'income', 'both', name='category_kind', native_enum=False, length=16), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], name=op.f('fk_category_parent_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_category_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('user_id', 'name', name='uq_category_user_id_name')
    )
    op.create_index(op.f('ix_category_user_id'), 'category', ['user_id'], unique=False)
    op.create_table('goal',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_amount >= 0', name=op.f('ck_goal_current_non_negative')),
    sa.CheckConstraint('target_amount > 0', name=op.f('ck_goal_target_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_goal_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal'))
    )
    op.create_index(op.f('ix_goal_user_id'), 'goal', ['user_id'], unique=False)
    op.create_table('investment',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('stock', 'fii', 'crypto', 'fixed_income', 'treasury', 'etf', 'other', name='investment_type', native_enum=False, length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('institution', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('average_price >= 0', name=op.f('ck_investment_average_price_non_negative')),
    sa.CheckConstraint('current_price >= 0', name=op.f('ck_investment_current_price_non_negative')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_investment_quantity_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_investment_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investment'))
    )
    op.create_index(op.f('ix_investment_user_id'), 'investment', ['user_id'], unique=False)
    op.create_table('budget',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_budget_amount_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_budget_category_id_category'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_budget_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget')),
    sa.UniqueConstraint('user_id', 'month', 'category_id', name='uq_budget_user_id_month_category')
    )
    op.create_index(op.f('ix_budget_month'), 'budget', ['month'], unique=False)
    op.create_index(op.f('ix_budget_user_id'), 'budget', ['user_id'], unique=False)
    op.create_table('card',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('bank', sa.String(length=80), nullable=True),
    sa.Column('brand', sa.Enum('visa', 'mastercard', 'elo', 'amex', 'hipercard', 'other', name='card_brand', native_enum=False, length=16), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('closing_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('closing_day BETWEEN 1 AND 31', name=op.f('ck_card_closing_day_range')),
    sa.CheckConstraint('due_day BETWEEN 1 AND 31', name=op.f('ck_card_due_day_range')),
    sa.CheckConstraint('limit_amount >= 0', name=op.f('ck_card_limit_non_negative')),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_card_account_id_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_card_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card'))
    )
    op.create_index(op.f('ix_card_user_id'), 'card', ['user_id'], unique=False)
    op.create_table('installment_plan',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('installments_count', sa.Integer(), nullable=False),
    sa.Column('first_due_date', sa.Date(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('installments_count >= 1', name=op.f('ck_installment_plan_count_positive')),
    sa.CheckConstraint('total_amount > 0', name=op.f('ck_installment_plan_total_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_installment_plan_account_id_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_installment_plan_card_id_card'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_installment_plan_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_installment_plan_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installment_plan'))
    )
    op.create_index(op.f('ix_installment_plan_user_id'), 'installment_plan', ['user_id'], unique=False)
    op.create_table('recurring_rule',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('type', sa.Enum('income', 'expense', 'transfer', name='transaction_type', native_enum=False, length=16), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', 'yearly', name='recurrence_frequency', native_enum=False, length=16), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('month_of_year', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_recurring_rule_amount_positive')),
    sa.CheckConstraint('day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31', name=op.f('ck_recurring_rule_day_of_month_range')),
    sa.CheckConstraint('weekday IS NULL OR weekday BETWEEN 0 AND 6', name=op.f('ck_recurring_rule_weekday_range')),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_recurring_rule_account_id_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_recurring_rule_card_id_card'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_recurring_rule_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_recurring_rule_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_rule'))
    )
    op.create_index(op.f('ix_recurring_rule_user_id'), 'recurring_rule', ['user_id'], unique=False)
    op.create_table('transaction',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('income', 'expense', 'transfer', name='transaction_type', native_enum=False, length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('transfer_account_id', sa.UUID(), nullable=True),
    sa.Column('installment_plan_id', sa.UUID(), nullable=True),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.Column('recurring_rule_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_transaction_amount_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_transaction_account_id_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_transaction_card_id_card'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_transaction_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['installment_plan_id'], ['installment_plan.id'], name=op.f('fk_transaction_installment_plan_id_installment_plan'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurring_rule_id'], ['recurring_rule.id'], name=op.f('fk_transaction_recurring_rule_id_recurring_rule'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['account.id'], name=op.f('fk_transaction_transfer_account_id_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_transaction_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction'))
    )
    op.create_index(op.f('ix_transaction_account_id'), 'transaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_transaction_card_id'), 'transaction', ['card_id'], unique=False)
    op.create_index(op.f('ix_transaction_category_id'), 'transaction', ['category_id'], unique=False)
    op.create_index(op.f('ix_transaction_date'), 'transaction', ['date'], unique=False)
    op.create_index(op.f('ix_transaction_installment_plan_id'), 'transaction', ['installment_plan_id'], unique=False)
    op.create_index(op.f('ix_transaction_recurring_rule_id'), 'transaction', ['recurring_rule_id'], unique=False)
    op.create_index('ix_transaction_user_card_date', 'transaction', ['user_id', 'card_id', 'date'], unique=False)
    op.create_index('ix_transaction_user_date', 'transaction', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_index('ix_transaction_user_date', table_name='transaction')
    op.drop_index('ix_transaction_user_card_date', table_name='transaction')
    op.drop_index(op.f('ix_transaction_recurring_rule_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_installment_plan_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_category_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_card_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_account_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_recurring_rule_user_id'), table_name='recurring_rule')
    op.drop_table('recurring_rule')
    op.drop_index(op.f('ix_installment_plan_user_id'), table_name='installment_plan')
    op.drop_table('installment_plan')
    op.drop_index(op.f('ix_card_user_id'), table_name='card')
    op.drop_table('card')
    op.drop_index(op.f('ix_budget_user_id'), table_name='budget')
    op.drop_index(op.f('ix_budget_month'), table_name='budget')
    op.drop_table('budget')
    op.drop_index(op.f('ix_investment_user_id'), table_name='investment')
    op.drop_table('investment')
    op.drop_index(op.f('ix_goal_user_id'), table_name='goal')
    op.drop_table('goal')
    op.drop_index(op.f('ix_category_user_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
