"""ticker e ultima cotacao no investimento

Revision ID: af57ca9c04e5
Revises: 7b2c9d451e88
Create Date: 2026-09-11 13:05:38.477164
"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'af57ca9c04e5'
down_revision: str | None = '7b2c9d451e88'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_app_user_id_auth_users', 'app_user', type_='foreignkey')
    op.add_column('investment', sa.Column('ticker', sa.String(length=16), nullable=True))
    op.add_column('investment', sa.Column('last_quote_price', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('investment', sa.Column('last_quote_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_investment_ticker'), 'investment', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_ticker'), table_name='investment')
    op.drop_column('investment', 'last_quote_at')
    op.drop_column('investment', 'last_quote_price')
    op.drop_column('investment', 'ticker')
    op.create_foreign_key('fk_app_user_id_auth_users', 'app_user', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###
